name: Release to JSR

on:
  workflow_run:
    workflows: ["Test Deno"]
    types:
      - completed
    branches:
      - main

jobs:
  publish-jsr:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Check if commit has a version tag
        id: check_tag
        run: |
          # Get all tags pointing to this commit
          TAGS=$(git tag --points-at HEAD)
          VERSION_TAG=""

          for tag in $TAGS; do
            if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              VERSION_TAG=$tag
              break
            fi
          done

          if [ -z "$VERSION_TAG" ]; then
            echo "❌ No version tag (v[0-9]+.[0-9]+.[0-9]+) found on this commit"
            exit 1
          fi

          echo "✓ Found version tag: $VERSION_TAG"
          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Log workflow context
        run: |
          echo "Publishing to JSR for tag: ${{ steps.check_tag.outputs.version_tag }}"
          echo "Commit SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Test Deno workflow completed successfully - proceeding with publication"

      - name: Publish to JSR
        run: |
          echo "Publishing to JSR registry..."
          npx jsr --no-check publish
          echo "✓ Successfully published to JSR"
