name: Publish to GitHub Releases

on:
  workflow_run:
    workflows: ["Publish to JSR"]
    types:
      - completed

jobs:
  build-release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      contains(github.event.workflow_run.head_commit.message, 'chore: tag version v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno/npm
            ~/.deno
          key: ${{ runner.os }}-npm-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build binaries
        run: deno task build

      - name: Get version from tag
        id: get_version
        run: |
          # Get the latest tag
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "VERSION=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "Using version: ${TAG_NAME}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            bin/*.zip
            bin/templates.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          tag_name: ${{ steps.get_version.outputs.VERSION }}
