name: Publish to JSR

on:
  workflow_run:
    workflows: ["Test Installer"]
    types:
      - completed
    # We can't specify tags here, so we'll filter in the job
    # using github.event.workflow_run.head_branch

jobs:
  # This job relies on the test-installer job in the test-install.yml workflow
  publish-jsr:
    # Only run if the test-installer workflow succeeded and it was triggered by a tag
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish to JSR
        run: npx jsr publish --no-check
